
import java.util.LinkedList;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author raria_000
 */
public class Find extends javax.swing.JDialog {

    /**
     * Creates new form Find
     */
    private String searchValue;
    private JNotepad parentFrame;
    private LinkedList <Integer>position;
    private JTextArea textArea;
    private int lastIndexViewed;
    public Find(java.awt.Frame parent, boolean modal, JNotepad parentFrame) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        this.parentFrame = parentFrame;
        ButtonGroup bg = new ButtonGroup();
        bg.add(upRadio);
        bg.add(downRadio);
        upRadio.setSelected(true);
        
        position = new LinkedList<>();
        lastIndexViewed = 0;
    }
    public void populateFindList()
    {
        if(searchValue.length() == 0)
            return;
        while(true)
        {
            int indexOfNextFind;
            
            if(position.isEmpty())
            {
                indexOfNextFind = textArea.getText().indexOf(searchValue);
                if (indexOfNextFind == -1)
                    break;
                position.add(indexOfNextFind);
            }
            else
            {
                 indexOfNextFind = textArea.getText().indexOf(searchValue, position.getLast() + 1);
                if (indexOfNextFind == -1)
                    break;
                position.add(indexOfNextFind);
            }
            
        }
       
            
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        findTextField = new javax.swing.JTextField();
        findBtn = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        upRadio = new javax.swing.JRadioButton();
        downRadio = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Find");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Find what: ");

        findTextField.setColumns(50);
        findTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        findBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        findBtn.setText("Find Next");
        findBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findBtnActionPerformed(evt);
            }
        });

        cancel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cancel.setText("Cancel");
        cancel.setDefaultCapable(false);
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Direction");

        upRadio.setText("Up");

        downRadio.setText("Down");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(findTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(downRadio)
                        .addComponent(upRadio)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(findBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(findTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(upRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(downRadio)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void findBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findBtnActionPerformed
        
        String textFieldValue = findTextField.getText();
        textArea = parentFrame.getTextArea();
        
        if(searchValue == null)
        {
            lastIndexViewed = 0;
            searchValue = textFieldValue;
            populateFindList();
            if(position.isEmpty())
                return;
            parentFrame.selectText(position, searchValue, lastIndexViewed, downRadio.isSelected());
            
           
        }
        else if(!searchValue.equals(textFieldValue))
        {
            //new find requested, so populate new list and highlight first index
            lastIndexViewed = 0;
            searchValue = textFieldValue;
            position.clear();
            populateFindList();
            parentFrame.selectText(position, searchValue, lastIndexViewed, downRadio.isSelected());
            
        }
        else
        {
            //existing find, check whether to find forward or back
            if (downRadio.isSelected())
            {
                if(lastIndexViewed + 1 > position.size() - 1)
                {
                    JOptionPane.showMessageDialog(this, "Cannot find: '" + searchValue + "'");
                    return;
                }
                lastIndexViewed++;
                parentFrame.selectText(position, searchValue, lastIndexViewed, true);
            }
            else
            {
                if(lastIndexViewed -1 < 0)
                {
                    JOptionPane.showMessageDialog(this, "Cannot find: '" + searchValue + "'");
                    return;
                }
                lastIndexViewed--;
                parentFrame.selectText(position, searchValue, lastIndexViewed, false);
            }
        }
    }//GEN-LAST:event_findBtnActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        
        setVisible(false);
        
    }//GEN-LAST:event_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Find.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Find.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Find.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Find.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Find dialog = new Find(new javax.swing.JFrame(), true, new JNotepad());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JRadioButton downRadio;
    private javax.swing.JButton findBtn;
    private javax.swing.JTextField findTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton upRadio;
    // End of variables declaration//GEN-END:variables
}
